### ISSUE TITLE
5.3.0 breaks prebuild tests

### ISSUE THREAD

**Issue by vweevers** [cmake-js/cmake-js#186]
Over at [`prebuild`](https://github.com/prebuild/prebuild) I noticed AppVeyor builds starting failing on integration tests with `cmake-js`. I then tested it locally and found that `cmake-js@5.2.0` is the last known working version. Apologies I can't get more specific than that. Though I help to maintain `prebuild` I'm not familiar with its `cmake-js` integration or `cmake-js` itself.

To reproduce (with Visual Studio 2015, which is AppVeyor's default), run:

```
git clone git@github.com:prebuild/prebuild.git && cd prebuild
npm i && npm t
```

Relevant log:

<details><summary>Click to expand</summary>

```
prebuild info begin Prebuild version 9.0.0
prebuild info build Preparing to prebuild native@1.0.0 for node 8.11.1 on win32-x64 using cmake-js
ERR! OMG Command failed: "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationVersion
ERR! OMG The system cannot find the path specified.
ERR! OMG 
ERR! OMG The system cannot find the path specified.
ERR! OMG 
ERR! OMG Command failed: "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationVersion
ERR! OMG The system cannot find the path specified.
ERR! OMG 
ERR! OMG The system cannot find the path specified.
ERR! OMG 
```

</details>

**Comment by unbornchikken** [comment]
What about 5.3.1?

**Comment by vweevers** [comment]
It looks like it was fixed for x64, tests still fail on x86: https://github.com/prebuild/prebuild/pull/254

**Comment by unbornchikken** [comment]
Did you add arch="ia32" to package.json's cmake-js settings? 

https://github.com/cmake-js/cmake-js/issues/188

It looks like our new vswhere based toolset detection makes this settings as mandatory. I'll look into this, but the workaround should work.

**Comment by vweevers** [comment]
If understand it correctly: in 5.2.0 and below, the process arch of `node` unintentionally triggered the right toolset to be selected? IMO that's actually desirable.

It's how various `prebuild*` tools work as well. In CI it makes it easy to prebuild binaries for different architectures (with a single `package.json`). It's also a good practice for local usage; matching up the bitness of a native module to the bitness of node just avoids a whole lot of issues.

**Comment by unbornchikken** [comment]
Fixed as of 5.2.2.

**Comment by unbornchikken** [comment]
I mean 5.3.2

**Comment by vweevers** [comment]
Still failing:

<details>
<summary>Click to expand</summary>

```
info TOOL Using Visual Studio 14 2015 ARM generator.
info CMD CLEAN
info RUN cmake -E remove_directory "D:\Projecten\GitHub\prebuild\prebuild\test\native-module-cmake\build"
info CMD CONFIGURE
info RUN cmake "D:\Projecten\GitHub\prebuild\prebuild\test\native-module-cmake" --no-warn-unused-cli -G"Visual Studio 14 2015 ARM" -DCMAKE_JS_VERSION="5.3.2" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_RUNTIME_OUTPUT_DIRECTORY="D:\Projecten\GitHub\prebuild\prebuild\test\native-module-cmake\build" -DCMAKE_JS_INC="C:\Users\vweevers\.cmake-js\node-ia32\v8.11.1\include\node" -DCMAKE_JS_SRC="D:/Projecten/GitHub/prebuild/prebuild/node_modules/cmake-js/lib/cpp/win_delay_load_hook.cc" -DNODE_RUNTIME="node" -DNODE_RUNTIMEVERSION="8.11.1" -DNODE_ARCH="ia32" -DCMAKE_JS_LIB="C:\Users\vweevers\.cmake-js\node-ia32\v8.11.1\win-x86\node.lib" -DCMAKE_SHARED_LINKER_FLAGS="/DELAYLOAD:NODE.EXE /SAFESEH:NO"
info CMD BUILD
info RUN cmake --build "D:\Projecten\GitHub\prebuild\prebuild\test\native-module-cmake\build" --config Release
ERR! OMG Process terminated: 1
```

</details>

Might be a separate issue. `cmake-js` doesn't show the error (only an exit code of 1) but running its last step manually reveals:

<details>
<summary>Click to expand</summary>

```
$ cmake --build "D:\Projecten\GitHub\prebuild\prebuild\test\native-module-cmake\build" --config Release
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

node.lib(node.exe) : fatal error LNK1112: module machine type 'X86' conflicts with target machine type 'ARM' [D:\Projecten\Gi tHub\prebuild\prebuild\test\native-module-cmake\build\native.vcxproj]
```

</details>

Do you want to continue discussion over at #188?
